name: playground_for_dart
description: Simple examples that help you get started with Appwrite + Dart (=❤️).
# version: 1.0.0
#homepage: https://www.example.com
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_appwrite: ^27.0.0

dev_dependencies:
  lints: ^6.0.0
